name: Mazda2MQTT
version: "2.0.0"
slug: mazda2mqtt
description: A Home Assistant add-on to run Mazda2MQTT with configurable regions and MQTT settings.
arch:
  - aarch64
  - amd64
  - armv7
  - i386
startup: application
init: false
boot: auto
options:
  mazda_email: ""      # Changed from mazda_username
  mazda_password: ""
  mazda_region: "MME"
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_user: ""
  mqtt_password: ""

schema:
  mazda_email: str     # Changed from mazda_username
  mazda_password: str
  mazda_region: str
  mqtt_host: str
  mqtt_port: int
  mqtt_user: str
  mqtt_password: str

environment:
  MAZDA_EMAIL: "{options.mazda_email}"    # Changed to match app.py
  MAZDA_PASSWORD: "{options.mazda_password}"
  MAZDA_REGION: "{options.mazda_region}"
  MQTT_BROKER: "{options.mqtt_host}"
  MQTT_PORT: "{options.mqtt_port}"
  MQTT_USER: "{options.mqtt_user}"
  MQTT_PASSWORD: "{options.mqtt_password}"